server:
  port: 5000

mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER

spring:
  datasource:

#    url: jdbc:mysql://localhost:3306/insurancecompanydb
#    username: ecommerceapp
#    password: ecommerceapp
#    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
# uncomment this code if you don't have the bank created and populated with the default ROLES
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expirationTime: 1800000
  secretKey: samucatezu

confirmation:
  token:
    time: 15

