server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurancecompanydb
    username: ecommerceapp
    password: ecommerceapp
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: barbosasamuel24@gmail.com
    password: senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expirationTime: 1800000
  secretKey: samucatezu

confirmation:
  token:
    time: 15

#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#
##spring:
##  datasource:
##    password: wAvyUtjXHgmpW1YatnldMM9pA_MSEHuv
##    url: jdbc:postgresql://isilo.db.elephantsql.com:5432/onqyqgrc
##    username: onqyqgrc
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/insurancecompanytestdb?createDatabaseIfNotExist=true
#    username: ecommerceapp
#    password: ecommerceapp
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#    show-sql: true
#
#  spring:
#    mvc:
#      pathmatch:
#        matching-strategy: ant_path_matcher
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL}
#    password: ${MAIL_PASS}
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
#jwt:
#  expirationTime: 1800000
#  secretKey: frog-lion-monkey-penguin-tiger87
#
#confirmation:
#  token:
#    time: 15